// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TherapyApp.Data.Concrete.EntityFramework.Contexts;

#nullable disable

namespace TherapyApp.Data.Migrations
{
    [DbContext(typeof(TherapyAppContext))]
    [Migration("20230727061602_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "83474a87-b307-4e35-89af-1007675e899f",
                            RoleId = "0597f004-c4dc-4eba-bf7f-a7016d69ab7d"
                        },
                        new
                        {
                            UserId = "f2a5b5d4-45ee-477b-b477-9eece5eb805a",
                            RoleId = "aaafa58f-bc74-46ae-b2a2-bf82b78e26e5"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TherapyApp.Entity.Concrete.Advisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .HasColumnType("TEXT");

                    b.Property<int>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Education")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Advisors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Erdinç Dursun, lisans eğitimini 2021 yılında Gazi Üniversitesi Rehberlik ve Psikolojik Danışmanlık alanında “Temel Psikolojik İhtiyaçlar ile İnternet Bağımlılığı ve Diğer Kişisel Faktörler Arasındaki İlişki” konulu bitirme tezi ile tamamlamıştır. ",
                            BranchId = 1,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6851),
                            Education = "Gazi Üniversitesi Rehberlik ve Psikolojik",
                            FirstName = "Erdinç",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Dursun",
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6870),
                            PhotoUrl = "erdinc-dursun.jpg",
                            Price = 500m,
                            Url = "erdinc-dursun-1"
                        },
                        new
                        {
                            Id = 2,
                            About = "Büşra Dursun, lisans eğitimini 2021 yılında Gazi Üniversitesi Rehberlik ve Psikolojik Danışmanlık alanında “Temel Psikolojik İhtiyaçlar ile İnternet Bağımlılığı ve Diğer Kişisel Faktörler Arasındaki İlişki” konulu bitirme tezi ile tamamlamıştır. ",
                            BranchId = 2,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6886),
                            Education = "Beykent Üniversitesi Rehberlik ve Psikolojik",
                            FirstName = "Büşra",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Dursun",
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6886),
                            PhotoUrl = "busra-dursun.jpg",
                            Price = 950m,
                            Url = "busra-dursun-2"
                        },
                        new
                        {
                            Id = 3,
                            About = "Ayse Hafsa Doğan, lisans eğitimini 2021 yılında Gazi Üniversitesi Rehberlik ve Psikolojik Danışmanlık alanında “Temel Psikolojik İhtiyaçlar ile İnternet Bağımlılığı ve Diğer Kişisel Faktörler Arasındaki İlişki” konulu bitirme tezi ile tamamlamıştır. ",
                            BranchId = 3,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6891),
                            Education = "İstanbul Üniversitesi Rehberlik ve Psikolojik",
                            FirstName = "Ayşe Hafsa",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Doğan",
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6892),
                            PhotoUrl = "ayse-hafsa-dogan.jpg",
                            Price = 350m,
                            Url = "ayse-hafsa-dogan-3"
                        },
                        new
                        {
                            Id = 4,
                            About = "Ömer Ayaz Dursun, lisans eğitimini 2021 yılında Gazi Üniversitesi Rehberlik ve Psikolojik Danışmanlık alanında “Temel Psikolojik İhtiyaçlar ile İnternet Bağımlılığı ve Diğer Kişisel Faktörler Arasındaki İlişki” konulu bitirme tezi ile tamamlamıştır. ",
                            BranchId = 4,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6895),
                            Education = "Marmara Üniversitesi Rehberlik ve Psikolojik",
                            FirstName = "Ömer Ayaz",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Dursun",
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6896),
                            PhotoUrl = "omer-ayaz-dursun.jpg",
                            Price = 900m,
                            Url = "omer-ayaz-dursun-4"
                        },
                        new
                        {
                            Id = 5,
                            About = "Ömer Ayaz Dursun, lisans eğitimini 2021 yılında Gazi Üniversitesi Rehberlik ve Psikolojik Danışmanlık alanında “Temel Psikolojik İhtiyaçlar ile İnternet Bağımlılığı ve Diğer Kişisel Faktörler Arasındaki İlişki” konulu bitirme tezi ile tamamlamıştır. ",
                            BranchId = 5,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6900),
                            Education = "Gazi Üniversitesi Rehberlik ve Psikolojik",
                            FirstName = "Zeynep Serra",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Dogan",
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6901),
                            PhotoUrl = "zeynep-serra-dogan.jpg",
                            Price = 700m,
                            Url = "zeynep-serra-dogan-5"
                        },
                        new
                        {
                            Id = 6,
                            About = "Nazlı Öztürk, lisans eğitimini 2021 yılında Adnan Menderes Üniversitesi Rehberlik ve Psikolojik Danışmanlık alanında “Temel Psikolojik İhtiyaçlar ile İnternet Bağımlılığı ve Diğer Kişisel Faktörler Arasındaki İlişki” konulu bitirme tezi ile tamamlamıştır. ",
                            BranchId = 6,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6904),
                            Education = "Adnan Menderes Üniversitesi Rehberlik ve Psikolojik",
                            FirstName = "Nazlı",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Öztürk",
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6905),
                            PhotoUrl = "nazli-ozturk.jpg",
                            Price = 700m,
                            Url = "nazli-ozturk-6"
                        },
                        new
                        {
                            Id = 7,
                            About = "Erdi Dursun, lisans eğitimini 2021 yılında İstanbul Üniversitesi Rehberlik ve Psikolojik Danışmanlık alanında “Temel Psikolojik İhtiyaçlar ile İnternet Bağımlılığı ve Diğer Kişisel Faktörler Arasındaki İlişki” konulu bitirme tezi ile tamamlamıştır. ",
                            BranchId = 3,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6908),
                            Education = "İstanbul Üniversitesi Rehberlik ve Psikolojik",
                            FirstName = "Erdi",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Dursun",
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6909),
                            PhotoUrl = "erdi-dursun.jpg",
                            Price = 650m,
                            Url = "erdi-dursun-7"
                        },
                        new
                        {
                            Id = 8,
                            About = "Özübek, lisans eğitimini 2021 yılında Arel Üniversitesi Rehberlik ve Psikolojik Danışmanlık alanında “Temel Psikolojik İhtiyaçlar ile İnternet Bağımlılığı ve Diğer Kişisel Faktörler Arasındaki İlişki” konulu bitirme tezi ile tamamlamıştır. ",
                            BranchId = 7,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6912),
                            Education = "Arel Üniversitesi Rehberlik ve Psikolojik",
                            FirstName = "Ahmet Tuğra",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Özübek",
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6913),
                            PhotoUrl = "ahmet-tugra-ozubek.jpg",
                            Price = 100m,
                            Url = "ahmet-tugra-ozubek-8"
                        },
                        new
                        {
                            Id = 9,
                            About = "Arzu Öztürk, lisans eğitimini 2021 yılında Vakfıkebir Üniversitesi Rehberlik ve Psikolojik Danışmanlık alanında “Temel Psikolojik İhtiyaçlar ile İnternet Bağımlılığı ve Diğer Kişisel Faktörler Arasındaki İlişki” konulu bitirme tezi ile tamamlamıştır. ",
                            BranchId = 8,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6916),
                            Education = "Vakfıkebir Üniversitesi Rehberlik ve Psikolojik",
                            FirstName = "Arzu",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Öztürk",
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6917),
                            PhotoUrl = "arzu-ozturk.jpg",
                            Price = 700m,
                            Url = "arzu-ozturk-9"
                        },
                        new
                        {
                            Id = 10,
                            About = "Şeyda Nur Doğan, lisans eğitimini 2021 yılında Anadolu Üniversitesi Rehberlik ve Psikolojik Danışmanlık alanında “Temel Psikolojik İhtiyaçlar ile İnternet Bağımlılığı ve Diğer Kişisel Faktörler Arasındaki İlişki” konulu bitirme tezi ile tamamlamıştır. ",
                            BranchId = 6,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6921),
                            Education = "Anadolu Üniversitesi Rehberlik ve Psikolojik",
                            FirstName = "Şeyda Nur",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Doğan",
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6921),
                            PhotoUrl = "seyda-nur-dogan.jpg",
                            Price = 320m,
                            Url = "seyda-nur-dogan-10"
                        },
                        new
                        {
                            Id = 11,
                            About = "Abdul Öztürk, lisans eğitimini 2021 yılında Vakfıkebir Üniversitesi Rehberlik ve Psikolojik Danışmanlık alanında “Temel Psikolojik İhtiyaçlar ile İnternet Bağımlılığı ve Diğer Kişisel Faktörler Arasındaki İlişki” konulu bitirme tezi ile tamamlamıştır. ",
                            BranchId = 1,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6925),
                            Education = "Vakfıbekir Üniversitesi Rehberlik ve Psikolojik",
                            FirstName = "Abdul",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Öztürk",
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6925),
                            PhotoUrl = "abdul-ozturk.jpg",
                            Price = 190m,
                            Url = "abdul-ozturk-11"
                        },
                        new
                        {
                            Id = 12,
                            About = "Habibe Dursun, lisans eğitimini 2021 yılında Sivas Üniversitesi Rehberlik ve Psikolojik Danışmanlık alanında “Temel Psikolojik İhtiyaçlar ile İnternet Bağımlılığı ve Diğer Kişisel Faktörler Arasındaki İlişki” konulu bitirme tezi ile tamamlamıştır. ",
                            BranchId = 8,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6929),
                            Education = "Sivas Üniversitesi Rehberlik ve Psikolojik",
                            FirstName = "Habibe",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Dursun",
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 910, DateTimeKind.Local).AddTicks(6930),
                            PhotoUrl = "habibe-dursun.jpg",
                            Price = 290m,
                            Url = "habibe-dursun-12"
                        });
                });

            modelBuilder.Entity("TherapyApp.Entity.Concrete.AdvisorCategory", b =>
                {
                    b.Property<int>("AdvisorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AdvisorId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("AdvisorCategories");

                    b.HasData(
                        new
                        {
                            AdvisorId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            AdvisorId = 1,
                            CategoryId = 5
                        },
                        new
                        {
                            AdvisorId = 1,
                            CategoryId = 6
                        },
                        new
                        {
                            AdvisorId = 1,
                            CategoryId = 10
                        },
                        new
                        {
                            AdvisorId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            AdvisorId = 2,
                            CategoryId = 3
                        },
                        new
                        {
                            AdvisorId = 2,
                            CategoryId = 4
                        },
                        new
                        {
                            AdvisorId = 2,
                            CategoryId = 6
                        },
                        new
                        {
                            AdvisorId = 2,
                            CategoryId = 9
                        },
                        new
                        {
                            AdvisorId = 3,
                            CategoryId = 7
                        },
                        new
                        {
                            AdvisorId = 3,
                            CategoryId = 10
                        },
                        new
                        {
                            AdvisorId = 4,
                            CategoryId = 2
                        },
                        new
                        {
                            AdvisorId = 4,
                            CategoryId = 5
                        },
                        new
                        {
                            AdvisorId = 4,
                            CategoryId = 10
                        },
                        new
                        {
                            AdvisorId = 5,
                            CategoryId = 10
                        },
                        new
                        {
                            AdvisorId = 5,
                            CategoryId = 8
                        },
                        new
                        {
                            AdvisorId = 6,
                            CategoryId = 1
                        },
                        new
                        {
                            AdvisorId = 6,
                            CategoryId = 3
                        },
                        new
                        {
                            AdvisorId = 6,
                            CategoryId = 4
                        },
                        new
                        {
                            AdvisorId = 6,
                            CategoryId = 9
                        },
                        new
                        {
                            AdvisorId = 7,
                            CategoryId = 7
                        },
                        new
                        {
                            AdvisorId = 7,
                            CategoryId = 10
                        },
                        new
                        {
                            AdvisorId = 8,
                            CategoryId = 11
                        },
                        new
                        {
                            AdvisorId = 9,
                            CategoryId = 12
                        },
                        new
                        {
                            AdvisorId = 10,
                            CategoryId = 1
                        },
                        new
                        {
                            AdvisorId = 10,
                            CategoryId = 3
                        },
                        new
                        {
                            AdvisorId = 10,
                            CategoryId = 4
                        },
                        new
                        {
                            AdvisorId = 10,
                            CategoryId = 9
                        },
                        new
                        {
                            AdvisorId = 11,
                            CategoryId = 2
                        },
                        new
                        {
                            AdvisorId = 11,
                            CategoryId = 5
                        },
                        new
                        {
                            AdvisorId = 11,
                            CategoryId = 6
                        },
                        new
                        {
                            AdvisorId = 11,
                            CategoryId = 10
                        },
                        new
                        {
                            AdvisorId = 12,
                            CategoryId = 12
                        });
                });

            modelBuilder.Entity("TherapyApp.Entity.Concrete.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(761),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(775),
                            Name = "Aile Danışmanı",
                            Url = "aile-danismani"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(781),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(781),
                            Name = "Klinik Psikolog",
                            Url = "klinik-danismani"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(784),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(791),
                            Name = "Çocuk ve Ergen Psikoloğu",
                            Url = "cocuk-ve-ergen-psikologu"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(808),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(809),
                            Name = "Çift Terapisti",
                            Url = "cift-terapisti"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(811),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(812),
                            Name = "Dil ve Konuşma Terapisti",
                            Url = "dil-ve-konusma-terapisti"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(814),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(815),
                            Name = "Uzman Nöropsikolog",
                            Url = "uzman-noropsikolog"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(816),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(817),
                            Name = "Fizyoterapist",
                            Url = "fizyoterapist"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(819),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(820),
                            Name = "Diyetisyen",
                            Url = "diyetisyen"
                        });
                });

            modelBuilder.Entity("TherapyApp.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4529),
                            Description = "Adli psikoloji, sanıkların soruşturma tekniği, görgü tanıklarının düşebileceği yanılsamaların saptanması, suç işleme yönteminin önceden bilinmesi, suçlu çocukların yeniden eğitim yoluyla toplum yaşamlarına uyumlarının sağlanması gibi konularla ilgilenen psikoloji dalıdır",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4541),
                            Name = "Adli Psikoloji",
                            Url = "adli-psikoloji"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4548),
                            Description = "Eş, çocuklar ve yakın akrabaları da kapsayan, aile üyelerini ilgilendiren sorunlara yönelik bir terapi formatıdır. Aile terapisi, ailede sorun ve çatışmaların belirlemesine ve bunların çözülmesine yardımcı olur.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4549),
                            Name = "Aile Terapisi",
                            Url = "aile-terapisi"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4552),
                            Description = "Anksiyete bir diğer adıyla kaygı bozukluğu, psikolojik bir rahatsızlıktır.Anksiyete bozukluğu olan kişilerde, yoğun, sürekli devam eden bir endişe hali ve günlük hayatta rastlanılan durumlara karşı korku vardır.Panik atak krizleriyle de kendini gösterebilir",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4553),
                            Name = "Anksiyete (kaygı) Bozuklukları",
                            Url = "anksiyete-bozukluklari"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4555),
                            Description = "İki uçlu duygudurum bozukluğu bir diğer adıyla manik-depresif hastalık, kişinin duygudurumunda, enerjisinde ve sosyal aktiviteleri tamamlama yetisinde bozulmalara neden olan psikolojik hastalıktır.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4556),
                            Name = "Bipolar Bozukluk",
                            Url = "bipolar-bozukluk"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4558),
                            Description = "boşanma sürecinde psikolojik sorunlar yaşamayı en aza indirmek, ortaya çıkması muhtemel olan yas ve ayrılıkla baş etmeyi kolaylaştırmak, bu sürecin çocuklar ve çiftler açısından en az hasarla atlatılmasını kolaylaştırmak için gerçekleştirilen bir hizmettir.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4558),
                            Name = "Boşanma Danışmanlığı",
                            Url = "bosanma-danismanligi"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4561),
                            Description = "bireylerin kendini psikolojik olarak iyi hissetmediği, çok uzun süreler devam edebilen ve günlük hayatı etkileyen psikolojik bir rahatsızlıktır",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4561),
                            Name = "Depresyon",
                            Url = "depresyon"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4563),
                            Description = "Uyku esnasında oluşan sorunlar veya aksiliklerin tamamına uyku bozukluğu denir",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4564),
                            Name = "Uyku Bozuklukları",
                            Url = "uyku-bozukluklari"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4566),
                            Description = "danışan birey veya grupla kariyer gelişimi ile ilgili sorunlarda (meslek seçimi, iş arama, vb.) profesyonel bir danışmanın yürütüldüğü ilişki biçimidir",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4567),
                            Name = "Kariyer Danışmanlığı",
                            Url = "kariyer-danismanligi"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4569),
                            Description = "Asperger sendromu esasen otistik spektrum bozukluğu yani kısaca OSB adı verilen geniş bir tanı yelpazesinin parçasıdır",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4569),
                            Name = "Asperger Sendromu",
                            Url = "asperger-sendromu"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4571),
                            Description = "ikili iletişim kuran taraflar arasında yapılan bir takım hayatlar sonucunda ortaya çıkar. ",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4572),
                            Name = "İletişim Problemleri",
                            Url = "iletisim-problemleri"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4574),
                            Description = "Yaralanma, hastalık, travma ya da yaşlılık gibi nedenlerle eksilme gösteren fonksiyonel hareketleri geri kazandırma amaçlı yapılan; elektrik akımı, sıcak ya da soğuk uygulaması, egzersizler ya da çeşitli uygulamalarla hastaların tedavisine verilen isimdir.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4575),
                            Name = "Fizyoterapist",
                            Url = "fizyoterapist"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4577),
                            Description = "Sağlık kurallarına uygun olarak kullanılmasını sağlayan, besin denetimini yapan, bu konularda fizyolojik, psikolojik ve sosyolojik olarak sağlıklı yaşam biçimlerinin benimsenmesi amacıyla bireyi ve toplumu bilgilendiren, bilinçlendiren kişilerdir.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 27, 9, 16, 1, 911, DateTimeKind.Local).AddTicks(4577),
                            Name = "Diyetisyen",
                            Url = "diyetisyen"
                        });
                });

            modelBuilder.Entity("TherapyApp.Entity.Concrete.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0597f004-c4dc-4eba-bf7f-a7016d69ab7d",
                            Description = "Admin role.",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "aaafa58f-bc74-46ae-b2a2-bf82b78e26e5",
                            Description = "User Role.",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "ae371bb7-e8dc-4668-96e0-816cbfc9556e",
                            Description = "Advisor Role",
                            Name = "Advisor",
                            NormalizedName = "ADVISOR"
                        });
                });

            modelBuilder.Entity("TherapyApp.Entity.Concrete.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "83474a87-b307-4e35-89af-1007675e899f",
                            AccessFailedCount = 0,
                            Address = "Pasa mah.Evren Sk.No:8/4 Sisli/İstanbul",
                            City = "İstanbul",
                            ConcurrencyStamp = "150b4295-3086-4512-bd08-f6578ee236c4",
                            DateOfBirth = new DateTime(1964, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "turkaydursun@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Türkay",
                            Gender = "Erkek",
                            LastName = "Dursun",
                            LockoutEnabled = true,
                            Name = " ",
                            NormalizedEmail = "TURKAYDURSUN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEEGW+WJzUY/qhKQRM1AQKZzWyNiR3yIg/yQl1IPT7l447MtEiaUr2Azo6NkKL2+T1A==",
                            PhoneNumber = "+9053547318",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "f2a5b5d4-45ee-477b-b477-9eece5eb805a",
                            AccessFailedCount = 0,
                            Address = "Pasa mahallesi dilek sokak no:8/4 sisli/istanbul",
                            City = "İstanbul",
                            ConcurrencyStamp = "16849ff4-d8dd-412e-a2b7-02d60de5f7c4",
                            DateOfBirth = new DateTime(1993, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "yunusemre@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Erdi",
                            Gender = "Erkek",
                            LastName = "Dursun",
                            LockoutEnabled = true,
                            Name = " ",
                            NormalizedEmail = "YUNUSEMRE@GMAIL.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEFmyD2cdu5ZcNicVgDbj9kcmoeqb9rRL1gaKLj0b/1dMJ0XTSFKDtNcxq/y/kh2rzQ==",
                            PhoneNumber = "+904556677888",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("TherapyApp.Entity.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TherapyApp.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TherapyApp.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("TherapyApp.Entity.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TherapyApp.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TherapyApp.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TherapyApp.Entity.Concrete.Advisor", b =>
                {
                    b.HasOne("TherapyApp.Entity.Concrete.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("TherapyApp.Entity.Concrete.AdvisorCategory", b =>
                {
                    b.HasOne("TherapyApp.Entity.Concrete.Advisor", "Advisor")
                        .WithMany("AdvisorCategories")
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TherapyApp.Entity.Concrete.Category", "Category")
                        .WithMany("AdvisorCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advisor");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TherapyApp.Entity.Concrete.Advisor", b =>
                {
                    b.Navigation("AdvisorCategories");
                });

            modelBuilder.Entity("TherapyApp.Entity.Concrete.Category", b =>
                {
                    b.Navigation("AdvisorCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
